baseURL = "/"
title = "Portfolio — [Mi Nombre]"
enableGitInfo = true
paginate = 24
disableKinds = ["RSS","sitemap"]

[params]
  author = "[Mi Nombre]"
  description = "Portfolio personal"

[[menu.main]]
  name = "Restores"
  url = "/restores"
  weight = 1

[[menu.main]]
  name = "Edits"
  url = "/edits"
  weight = 2

[[menu.main]]
  name = "Videos"
  url = "/videos"
  weight = 3

[[menu.main]]
  name = "Timeline"
  url = "/timeline"
  weight = 4
